# Use cases:
1.Sentence Similarity

2.Semantic Search

3.Clustering

In [ ]:
!pip install -U sentence-transformers


##Sentence Similarity



In [ ]:
from sentence_transformers import SentenceTransformer,util
model = SentenceTransformer('all-MiniLM-L6-v2')


In [ ]:
sentences = ['This framework generates embeddings for each input sentence',
    'Sentences are passed as a list of string.']

embeddings = model.encode(sentences)

for sentence, embedding in zip(sentences, embeddings):
    print("Sentence:", sentence)
    print("Embedding:", embedding)
    print("")


Cosine Similarity

In [4]:
emb1 = model.encode("I am eating Apple")
emb2 = model.encode("I like fruits")
cos_sim = util.cos_sim(emb1, emb2)
print("Cosine-Similarity:", cos_sim)

Cosine-Similarity: tensor([[0.5398]])


Compute cosine similarity between all pairs


In [26]:
# Compute cosine similarity between all pairs

sentences = ['A man is eating food.',
          'A man is eating a piece of bread.',
          'The girl is carrying a baby.',
          'A man is riding a horse.',
          'A woman is playing violin.',
          'Two men pushed carts through the woods.',
          'A man is riding a white horse on an enclosed ground.',
          'A monkey is playing drums.',
          'Someone in a gorilla costume is playing a set of drums.'
          ]

embeddings = model.encode(sentences)
cos_sim = util.cos_sim(embeddings, embeddings)

cos_sim


tensor([[1.0000, 0.9942, 0.9753, 0.9879, 0.9764, 0.9673, 0.9750, 0.9771, 0.9675],
        [0.9942, 1.0000, 0.9772, 0.9914, 0.9802, 0.9688, 0.9825, 0.9756, 0.9760],
        [0.9753, 0.9772, 1.0000, 0.9786, 0.9800, 0.9652, 0.9732, 0.9714, 0.9720],
        [0.9879, 0.9914, 0.9786, 1.0000, 0.9854, 0.9710, 0.9904, 0.9797, 0.9788],
        [0.9764, 0.9802, 0.9800, 0.9854, 1.0000, 0.9690, 0.9771, 0.9783, 0.9852],
        [0.9673, 0.9688, 0.9652, 0.9710, 0.9690, 1.0000, 0.9693, 0.9588, 0.9668],
        [0.9750, 0.9825, 0.9732, 0.9904, 0.9771, 0.9693, 1.0000, 0.9701, 0.9772],
        [0.9771, 0.9756, 0.9714, 0.9797, 0.9783, 0.9588, 0.9701, 1.0000, 0.9741],
        [0.9675, 0.9760, 0.9720, 0.9788, 0.9852, 0.9668, 0.9772, 0.9741, 1.0000]])

In [27]:
#Add all pairs to a list with their cosine similarity score like sen0 with sen1 , sen0 with sen2 etc.
#It is obvious that sen0 with sen0 = 1.000 and similarly sen1 with sen1 = 1.000 and so on

all_sentence_combinations = []
for i in range(len(cos_sim)-1):
    for j in range(i+1, len(cos_sim)):
        all_sentence_combinations.append((cos_sim[i][j], i, j))
all_sentence_combinations

[(tensor(0.9942), 0, 1),
 (tensor(0.9753), 0, 2),
 (tensor(0.9879), 0, 3),
 (tensor(0.9764), 0, 4),
 (tensor(0.9673), 0, 5),
 (tensor(0.9750), 0, 6),
 (tensor(0.9771), 0, 7),
 (tensor(0.9675), 0, 8),
 (tensor(0.9772), 1, 2),
 (tensor(0.9914), 1, 3),
 (tensor(0.9802), 1, 4),
 (tensor(0.9688), 1, 5),
 (tensor(0.9825), 1, 6),
 (tensor(0.9756), 1, 7),
 (tensor(0.9760), 1, 8),
 (tensor(0.9786), 2, 3),
 (tensor(0.9800), 2, 4),
 (tensor(0.9652), 2, 5),
 (tensor(0.9732), 2, 6),
 (tensor(0.9714), 2, 7),
 (tensor(0.9720), 2, 8),
 (tensor(0.9854), 3, 4),
 (tensor(0.9710), 3, 5),
 (tensor(0.9904), 3, 6),
 (tensor(0.9797), 3, 7),
 (tensor(0.9788), 3, 8),
 (tensor(0.9690), 4, 5),
 (tensor(0.9771), 4, 6),
 (tensor(0.9783), 4, 7),
 (tensor(0.9852), 4, 8),
 (tensor(0.9693), 5, 6),
 (tensor(0.9588), 5, 7),
 (tensor(0.9668), 5, 8),
 (tensor(0.9701), 6, 7),
 (tensor(0.9772), 6, 8),
 (tensor(0.9741), 7, 8)]

In [28]:
# Printing the highest similar sentences with their cosine similarity score
all_sentence_combinations = sorted(all_sentence_combinations, key=lambda x: x[0], reverse=True)

print("Top-5 most similar pairs:")
for score, i, j in all_sentence_combinations[0:5]:
    print("{} \t {} \t {:.4f}".format(sentences[i], sentences[j], cos_sim[i][j]))

Top-5 most similar pairs:
A man is eating food. 	 A man is eating a piece of bread. 	 0.9942
A man is eating a piece of bread. 	 A man is riding a horse. 	 0.9914
A man is riding a horse. 	 A man is riding a white horse on an enclosed ground. 	 0.9904
A man is eating food. 	 A man is riding a horse. 	 0.9879
A man is riding a horse. 	 A woman is playing violin. 	 0.9854


##Semantic Search

In [29]:
# This model is used because - "It presents a multilingual FAQ retrieval model trained on the MFAQ dataset, it ranks candidate answers according to a given question."
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('clips/mfaq')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py:364: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(


In [30]:
question = "How many models can I host on HuggingFace?"
answer_1 = "All plans come with unlimited private models and datasets."
answer_2 = "AutoNLP is an automatic way to train and deploy state-of-the-art NLP models, seamlessly integrated with the Hugging Face ecosystem."
answer_3 = "Based on how much training data and model variants are created, we send you a compute cost and payment link - as low as $10 per job."

query_embedding = model.encode(question)
corpus_embeddings = model.encode([answer_1, answer_2, answer_3])

print(util.semantic_search(query_embedding, corpus_embeddings))

[[{'corpus_id': 0, 'score': 0.5507141351699829}, {'corpus_id': 2, 'score': 0.49931809306144714}, {'corpus_id': 1, 'score': 0.45967182517051697}]]


Still the anwer for our question is not obtained but it returned the highest score where the answer of our question can be found

In [10]:
from transformers import pipeline

In [31]:
qa_model = pipeline("question-answering")
question = "How many models can I host on HuggingFace?"
context = "All plans come with unlimited private models and datasets."
qa_model(question = question, context = context)

No model was supplied, defaulted to distilbert/distilbert-base-cased-distilled-squad and revision 626af31 (https://huggingface.co/distilbert/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.


{'score': 0.7017179727554321, 'start': 20, 'end': 29, 'answer': 'unlimited'}

We got the answer as 'unlimited' here

##Clustering

In [14]:
from sklearn.cluster import KMeans
import numpy as np

embedder = SentenceTransformer('all-MiniLM-L6-v2')

# Corpus with example sentences
corpus = ['A man is eating food.',
          'A man is eating a piece of bread.',
          'Horse is eating grass.',
          'A man is eating pasta.',
          'A Woman is eating Biryani.',
          'The girl is carrying a baby.',
          'The baby is carried by the woman',
          'A man is riding a horse.',
          'A man is riding a white horse on an enclosed ground.',
          'A monkey is playing drums.',
          'Someone in a gorilla costume is playing a set of drums.',
          'A cheetah is running behind its prey.',
          'A cheetah chases prey on across a field.',
          'The cheetah is chasing a man who is riding the horse.',
          'man and women with their baby are watching cheetah in zoo'
          ]
corpus_embeddings = embedder.encode(corpus)
corpus_embeddings = corpus_embeddings /  np.linalg.norm(corpus_embeddings, axis=1, keepdims=True)

In [15]:
corpus_embeddings[0]

array([ 3.32415663e-02,  4.40607499e-03, -6.27700286e-03,  4.83787432e-02,
       -1.38702288e-01, -3.36174220e-02,  1.01128325e-01, -5.43849692e-02,
       -4.32477221e-02, -3.99410948e-02,  7.78632425e-03, -1.27489083e-02,
       -6.68302402e-02, -1.73866116e-02,  4.74505909e-02, -5.77242747e-02,
        1.01888388e-01, -9.11660900e-04,  8.22614655e-02, -5.03415987e-02,
        6.77303076e-02,  4.08765301e-02, -3.58018763e-02, -1.00682445e-01,
       -6.69356575e-03, -5.31686135e-02,  1.00335166e-01, -5.46136349e-02,
       -2.28481777e-02,  1.38387177e-02,  7.48658255e-02, -6.17880449e-02,
        6.39215931e-02,  1.62387174e-02, -5.32299168e-02, -3.86083834e-02,
        3.15276086e-02, -8.11529905e-02, -3.31432223e-02, -5.38496650e-04,
       -3.96068720e-03, -1.52733978e-02, -9.86401457e-04,  9.57987681e-02,
       -5.42920157e-02,  1.84571967e-02, -1.07143618e-01,  1.38884932e-02,
        3.94072458e-02, -2.69243810e-02, -9.15989354e-02, -1.14195086e-02,
        3.38137336e-02, -

In [18]:
clustering_model = KMeans(n_clusters=5)
clustering_model.fit(corpus_embeddings)
cluster_assignment = clustering_model.labels_
print(cluster_assignment)

[0 0 4 0 0 2 2 4 4 3 3 1 1 1 1]


/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [19]:
clustered_sentences = {}
for sentence_id, cluster_id in enumerate(cluster_assignment):
    if cluster_id not in clustered_sentences:
        clustered_sentences[cluster_id] = []

    clustered_sentences[cluster_id].append(corpus[sentence_id])
clustered_sentences

{0: ['A man is eating food.',
  'A man is eating a piece of bread.',
  'A man is eating pasta.',
  'A Woman is eating Biryani.'],
 4: ['Horse is eating grass.',
  'A man is riding a horse.',
  'A man is riding a white horse on an enclosed ground.'],
 2: ['The girl is carrying a baby.', 'The baby is carried by the woman'],
 3: ['A monkey is playing drums.',
  'Someone in a gorilla costume is playing a set of drums.'],
 1: ['A cheetah is running behind its prey.',
  'A cheetah chases prey on across a field.',
  'The cheetah is chasing a man who is riding the horse.',
  'man and women with their baby are watching cheetah in zoo']}